### PR TITLE
Miscellaneous changes to fix open issues

### PR DESCRIPTION
**Pull request by sumitmaggo**
This pull request will provide the fix for these pending issues: #9 #12 #13 
Changes done:
1) Changed JUNONIA_UFS to JUNONIA_US
2) Changed var_file_arg value so that it can be used properly as input argument in 'terraform console' 
3) Changing back to working directory in case of '-var-file' option so that 'terraform console' can run properly.
4) Added support to include variables which has integer values.
5) Remove state lock messages from 'terraform console' output.
6) Updating 'defaulthclvars' and 'defaultvars' based on its existing values.
7) Using 'val_lines' as value in defaulthclvars as function 'process_vars' calls the escape_value() function for HCL values.

### CODE REVIEW

**Comment by fprimex** [comment]
This is awesome, thanks! As the one big bottleneck on the progress for tfh, I feel like I should set expectations & disclose that I'm wrestling with a health issue right now. I am out of commission until I get that sorted. I'll know more by the middle of next week hopefully.

**Comment by sumitmaggo** [comment]
@fprimex Sad to hear that, hope its not a serious one. Take care and wish you a speedy recovery.

**Comment by samm-git** [comment]
@fprimex it is really sad to hear. I wish you to get well soon, hope it is nothing serious

**Comment by fprimex** [comment]
Thank you for the concern. Please don't worry for me though; should be able to address it within a few weeks at most. Not life threatening, just preventing me from being able to work.

**Comment by fprimex** [comment]
While GH is probably not the most appropriate place for health updates, I wanted to say things took an unexpected turn and I ended up with a pinched nerve (we think). Now I'm out pending a scan. I have to be put in a specific MRI with special equipment due to my cochlear implant, so things are delayed.

In the meantime, due to how this is affecting me I'm unable to code (or do many other things).

I provide "too much information" here just so people won't worry due to ominous, ambiguous updates. Sorry!

Please recall that as much as I've worked to make this tool useful, the officially supported API uses that you can file customer support tickets for are:

* Simple, direct uses of the endpoints with, e.g., `curl`.
* The tfe-go SDK.
* The `tfe` Terraform provider.
* The `remote` backend for Terraform.

Cheers

**Comment by jeremygaither** [comment]
@fprimex been there myself, my sympathies... hang in there!

**Comment by fprimex** [comment]
Hello and Happy New Year! I've read over the PR and everything looks in order, but I have not tested it. My plan would be to write failing tests in `master`, merge this into `master`, fix any lingering issues, and make a release.

If this sounds good to you, could you retarget this PR to `master`?

**Comment by fprimex** [comment]
I didn't know that I could change it myself, so I have done so. This is going into master, where there are some other things that need to be done before a new release can be cut. Thanks again!

**Comment by fprimex** [comment]
OK, so after merging this and writing tests it turned out that we both missed quite a lot. There are 4 different distinct cases to take into account - all of the permutations of supplying a config directory and `-var-file`. The changes necessary to handle all of this are reflected in `master`.

If you're open to `sh` coding suggestions, mine are:

* Use `$()` instead of backticks, which has been the recommendation of the standards group since sometime in the 70's or 80's

* Make sure you quote things that could have spaces (`cd "$working_dir"`)

* Use `$PWD` to get the working dir, as it is POSIX and absolute. Use `pwd -P` if you need to resolve symlinks

**Pull request merged**
